services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  spark:
    build:
      context: .
      dockerfile: Dockerfile.spark
    container_name: spark
    depends_on:
      - kafka
    ports:
      - "7077:7077"
      - "8081:8080"
    volumes:
      - ./spark-app:/spark-app

# ======== Docker commands =============



  # docker-compose up -d
  # docker-compose down -v
  # docker-compose build --no-cache

  # docker exec -it kafka kafka-topics --bootstrap-server kafka:9092 --list

  # docker exec -it kafka kafka-topics --bootstrap-server kafka:9092 --create --topic raw_audio_topic  --partitions 1 --replication-factor 1
  # docker exec -it kafka kafka-topics --bootstrap-server kafka:9092 --create --topic prediction_topic  --partitions 1 --replication-factor 1
  # docker exec -it kafka kafka-topics --bootstrap-server kafka:9092 --create --topic alert_event_topic --partitions 1 --replication-factor 1
  


  # docker exec -it spark spark-submit --master local[*] --packages org.apache.spark:spark-sql-kafka-0-10_2.13:4.1.1 /spark-app/stream_inference.py
  # docker exec -it kafka kafka-console-consumer --bootstrap-server kafka:9092 --topic prediction-topic --from-beginning
  





  # #docker exec -it kafka kafka-topics --bootstrap-server kafka:9092 --delete --topic <topic_name>